[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_PATHS = "firebase-applet-config.json,dist/**"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
