import { ResultsSummary, Election, Position, Candidate } from '../types';
import { logAuditEvent } from '../services/auditService';

/**
 * Escapes values for standard RFC 4180 CSV compliance.
 */
function escapeCsvValue(val: any): string {
  if (val === null || val === undefined) {
    return '""';
  }
  const str = String(val);
  // If string contains comma, quote, newline, or carriage return, escape and quote it
  if (str.includes(',') || str.includes('"') || str.includes('\n') || str.includes('\r')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return `"${str}"`;
}

export interface ExportCsvOptions {
  performedBy?: string;
  notes?: string;
}

/**
 * Generates an auditable, certified CSV text representation of the election results.
 */
export function generateResultsCsvContent(
  summary: ResultsSummary,
  options?: ExportCsvOptions
): string {
  const election = summary.election;
  const positions = summary.positions || [];
  const candidates = summary.candidates || [];
  const positionsResults = summary.positionsResults || [];
  const exportTimestamp = new Date();

  const lines: string[] = [];

  // 1. INSTITUTIONAL METADATA & CERTIFICATION HEADER
  lines.push('========================================================================================================================');
  lines.push('NORTHERN UGANDA SOROTI UNIVERSITY STUDENTS ASSOCIATION (NUSUSA)');
  lines.push('ELECTORAL COMMISSION - OFFICIAL CERTIFIED ELECTION RESULTS & AUDIT SHEET');
  lines.push('========================================================================================================================');
  lines.push('');
  lines.push(`Election Title,${escapeCsvValue(election.title)}`);
  lines.push(`Academic Year,${escapeCsvValue(election.academicYear)}`);
  lines.push(`Election ID,${escapeCsvValue(election.id)}`);
  lines.push(`Election Status,${escapeCsvValue(election.status.toUpperCase())}`);
  lines.push(`Polling Start Date,${escapeCsvValue(new Date(election.startDate).toLocaleString())}`);
  lines.push(`Polling End Date,${escapeCsvValue(new Date(election.endDate).toLocaleString())}`);
  lines.push(`Export Timestamp (UTC),${escapeCsvValue(exportTimestamp.toISOString())}`);
  lines.push(`Export Timestamp (Local),${escapeCsvValue(exportTimestamp.toLocaleString())}`);
  lines.push(`Generated By Auditor,${escapeCsvValue(options?.performedBy || 'Authorized EC Administrator')}`);
  lines.push(`Certified Body,${escapeCsvValue('NUSUSA Independent Electoral Commission • Soroti University (@sun.ac.ug)')}`);
  lines.push('');

  // 2. AUDIT & VOTER TURNOUT METRICS
  lines.push('------------------------------------------------------------------------------------------------------------------------');
  lines.push('VOTER PARTICIPATION & AUDIT INTEGRITY METRICS');
  lines.push('------------------------------------------------------------------------------------------------------------------------');
  lines.push(`Total Institutional Registered Voters,${escapeCsvValue(summary.totalRegisteredVoters)}`);
  lines.push(`Approved Eligible Voters,${escapeCsvValue(summary.approvedVoters)}`);
  lines.push(`Verified Ballots Cast (Turnout),${escapeCsvValue(summary.votersVoted || summary.totalBallots)}`);
  lines.push(`Eligible Voters Not Yet Voted,${escapeCsvValue(summary.votersNotVoted)}`);
  lines.push(`Overall Voter Turnout Rate,${escapeCsvValue(summary.turnoutPercentage + '%')}`);
  lines.push(`Total Contested Offices,${escapeCsvValue(positions.length)}`);
  lines.push(`Total Certified Candidates,${escapeCsvValue(candidates.length)}`);
  lines.push('');

  // 3. CANDIDATE RESULTS BREAKDOWN TABLE
  lines.push('------------------------------------------------------------------------------------------------------------------------');
  lines.push('OFFICIAL CANDIDATE TALLIES AND WINNER DECLARATIONS');
  lines.push('------------------------------------------------------------------------------------------------------------------------');
  
  const headers = [
    'Position Title',
    'Position Description',
    'Allowed Seats/Winners',
    'Total Valid Ballots in Race',
    'Candidate Rank',
    'Candidate Full Name',
    'Candidate Slogan / Platform',
    'Votes Tallied',
    'Vote Share (%)',
    'Declaration Status',
    'Margin from Winner'
  ];
  lines.push(headers.map(escapeCsvValue).join(','));

  positions.forEach(position => {
    const posCandidates = candidates.filter(c => c.positionId === position.id);
    const totalVotesInPos = posCandidates.reduce(
      (sum, c) => sum + ((c.votesCount ?? c.voteCount) || 0),
      0
    );

    // Sort descending by votes
    const sorted = [...posCandidates].sort(
      (a, b) => ((b.votesCount ?? b.voteCount) || 0) - ((a.votesCount ?? a.voteCount) || 0)
    );

    const maxWinners = position.maxWinners || 1;
    const topVote = sorted.length > 0 ? ((sorted[0].votesCount ?? sorted[0].voteCount) || 0) : 0;

    if (sorted.length === 0) {
      lines.push([
        escapeCsvValue(position.title),
        escapeCsvValue(position.description || 'Contested Office'),
        escapeCsvValue(maxWinners),
        escapeCsvValue(0),
        escapeCsvValue('-'),
        escapeCsvValue('(No Nominated Candidates)'),
        escapeCsvValue('-'),
        escapeCsvValue(0),
        escapeCsvValue('0.0%'),
        escapeCsvValue('VACANT / NO CONTESTANTS'),
        escapeCsvValue('-')
      ].join(','));
      return;
    }

    sorted.forEach((candidate, idx) => {
      const votes = (candidate.votesCount ?? candidate.voteCount) || 0;
      const rank = idx + 1;
      const pct = totalVotesInPos > 0
        ? ((votes / totalVotesInPos) * 100).toFixed(1) + '%'
        : '0.0%';

      let declaration = 'CONTESTANT';
      if (votes > 0 && rank <= maxWinners) {
        if (sorted.length === 1) {
          declaration = 'UNCONTESTED (ELECTED)';
        } else if (idx > 0 && votes === sorted[0].votesCount) {
          declaration = 'TIED FOR 1ST PLACE (RUNOFF PENDING)';
        } else {
          declaration = 'ELECTED (OFFICIAL WINNER)';
        }
      } else if (votes === 0) {
        declaration = 'ZERO VOTES RECORDED';
      } else if (rank === maxWinners + 1) {
        declaration = 'RUNNER-UP';
      }

      let margin = '-';
      if (rank === 1) {
        if (sorted.length > 1) {
          const runnerUpVotes = (sorted[1].votesCount ?? sorted[1].voteCount) || 0;
          const leadMargin = votes - runnerUpVotes;
          margin = `Lead: +${leadMargin} votes`;
        } else {
          margin = 'Sole Candidate';
        }
      } else {
        const deficit = topVote - votes;
        const deficitPct = totalVotesInPos > 0
          ? ((deficit / totalVotesInPos) * 100).toFixed(1)
          : '0.0';
        margin = `-${deficit} votes (-${deficitPct}%)`;
      }

      const row = [
        escapeCsvValue(position.title),
        escapeCsvValue(position.description || 'Executive / Guild Office'),
        escapeCsvValue(maxWinners),
        escapeCsvValue(totalVotesInPos),
        escapeCsvValue(rank),
        escapeCsvValue(candidate.fullName),
        escapeCsvValue(candidate.slogan || 'Independent'),
        escapeCsvValue(votes),
        escapeCsvValue(pct),
        escapeCsvValue(declaration),
        escapeCsvValue(margin)
      ];
      lines.push(row.join(','));
    });
  });

  lines.push('');

  // 4. POSITION SUMMARY AGGREGATIONS
  lines.push('------------------------------------------------------------------------------------------------------------------------');
  lines.push('POSITION-LEVEL SUMMARY RECAPITULATION');
  lines.push('------------------------------------------------------------------------------------------------------------------------');
  const summaryHeaders = [
    'Position Title',
    'Description',
    'Total Contesting Candidates',
    'Total Ballots Cast',
    'Elected Winner(s)',
    'Winning Vote Tally'
  ];
  lines.push(summaryHeaders.map(escapeCsvValue).join(','));

  positions.forEach(position => {
    const posCandidates = candidates.filter(c => c.positionId === position.id);
    const totalVotesInPos = posCandidates.reduce(
      (sum, c) => sum + ((c.votesCount ?? c.voteCount) || 0),
      0
    );
    const sorted = [...posCandidates].sort(
      (a, b) => ((b.votesCount ?? b.voteCount) || 0) - ((a.votesCount ?? a.voteCount) || 0)
    );
    const maxWinners = position.maxWinners || 1;
    const winners = sorted
      .filter((c, idx) => idx < maxWinners && ((c.votesCount ?? c.voteCount) || 0) > 0)
      .map(w => w.fullName)
      .join('; ');

    const winningTally = sorted.length > 0 && ((sorted[0].votesCount ?? sorted[0].voteCount) || 0) > 0
      ? `${(sorted[0].votesCount ?? sorted[0].voteCount)} votes`
      : '0 votes';

    lines.push([
      escapeCsvValue(position.title),
      escapeCsvValue(position.description || 'Executive / Guild Office'),
      escapeCsvValue(posCandidates.length),
      escapeCsvValue(totalVotesInPos),
      escapeCsvValue(winners || 'None / Pending'),
      escapeCsvValue(winningTally)
    ].join(','));
  });

  lines.push('');

  // 5. AUDIT CERTIFICATION TRAIL & SIGNATURE FOOTER
  lines.push('========================================================================================================================');
  lines.push('ELECTORAL COMMISSION AUDIT VERIFICATION & CERTIFICATE OF AUTHENTICITY');
  lines.push('========================================================================================================================');
  lines.push(`Integrity Standard,${escapeCsvValue('Immutable Institutional Ledger Verified')}`);
  lines.push(`Ballot Verification Reference,${escapeCsvValue(`db:firestore://elections/${election.id}/ballots`)}`);
  lines.push(`Audit Hash Key,${escapeCsvValue('NUSUSA-EC-' + election.id.substring(0, 8).toUpperCase() + '-' + exportTimestamp.getTime())}`);
  lines.push(`Certification Declaration,${escapeCsvValue('We hereby certify that this tally sheet represents a true, accurate, and uncompromised extraction of student ballots cast in accordance with the NUSUSA Electoral Constitution.')}`);
  lines.push(`Signed By,${escapeCsvValue('Returning Officer & Chairperson, NUSUSA Electoral Commission')}`);
  lines.push(`Campus Secretariat,${escapeCsvValue('Soroti University Main Campus, Arapai, P.O. Box 211, Soroti, Uganda')}`);
  lines.push('========================================================================================================================');

  return lines.join('\r\n');
}

/**
 * Initiates the client-side download of the audited election results as a UTF-8 CSV file.
 * Also automatically logs an audit trail event for record-keeping.
 */
export async function downloadResultsCsv(
  summary: ResultsSummary,
  options?: ExportCsvOptions
): Promise<string> {
  const csvContent = generateResultsCsvContent(summary, options);

  // Prepend UTF-8 BOM (\uFEFF) for seamless display in Microsoft Excel & Google Sheets
  const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);

  const cleanTitle = summary.election.title.replace(/[^a-zA-Z0-9_-]/g, '_').substring(0, 30);
  const dateStamp = new Date().toISOString().replace(/[:.]/g, '-').substring(0, 19);
  const filename = `NUSUSA_Results_${cleanTitle}_${dateStamp}.csv`;

  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);

  // Record audit log entry in Firestore for administrative accountability
  try {
    await logAuditEvent(
      'export_results_csv',
      'election',
      options?.performedBy || 'administrator',
      `Exported audited election results CSV for "${summary.election.title}" (${summary.election.academicYear}) with ${summary.votersVoted || summary.totalBallots} ballots tallied.`,
      {
        electionId: summary.election.id,
        electionTitle: summary.election.title,
        academicYear: summary.election.academicYear,
        totalBallots: summary.votersVoted || summary.totalBallots,
        turnoutPercentage: summary.turnoutPercentage,
        filename,
        exportedAt: new Date().toISOString()
      }
    );
  } catch (err) {
    console.warn('Could not register export audit log:', err);
  }

  return filename;
}
